spring:
  application:
    name: africoin-admin-service
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: 'UTC'
        temp:
          use_jdbc_metadata_default: false
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 20MB
hibernate:
  jdbc:
    time_zone: 'UTC'
server:
  port: 8012
  forward-headers-strategy: none
management:
  endpoints:
    web:
      exposure:
        include: health,info
token:
  expiry-time-in-minutes:
    access: 10
    refresh: 30
logging:
  level:
    org.springframework: INFO
    com.afrione.africoinservice: debug
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR

africoin:
  client-key:
    android: '138245b7d467fe06333292af44228d01'
    ios: 'ec2f97eac62f523c33a1042adeec531e'
    web: '8a26d5ddbb7ff954da3fefed3551088c'

springdoc:
  override-with-generic-response: false


isTestEnv: true
